/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        "surface-dim": "#dcd8e5",
        "on-primary-container": "#dad7ff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "bg-dark-secondary": "#12151C",
        "bg-dark-primary": "#0B0E14",
        border: "#D8DAE0",
        "bg-secondary": "#F5F6F8",
        "secondary-fixed-dim": "#c6c6cd",
        secondary: "#5d5e64",
        success: "#16A34A",
        tertiary: "#7e3000",
        "tertiary-container": "#a44100",
        "surface-container": "#f0ecf9",
        "secondary-fixed": "#e2e2e9",
        "primary-fixed": "#e2dfff",
        "on-tertiary-fixed": "#351000",
        "surface-container-high": "#eae6f4",
        "primary-container": "#4f46e5",
        "on-primary": "#ffffff",
        "surface-bright": "#fcf8ff",
        "tertiary-fixed": "#ffdbcc",
        "secondary-container": "#dfdfe6",
        "inverse-primary": "#c3c0ff",
        "on-tertiary-container": "#ffd2be",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e4e1ee",
        "on-surface": "#1b1b24",
        "on-primary-fixed-variant": "#3323cc",
        "outline-variant": "#c7c4d8",
        "on-secondary-fixed-variant": "#45474c",
        "accent-subtle": "#EEF0FF",
        outline: "#777587",
        "surface-variant": "#e4e1ee",
        "error-container": "#ffdad6",
        error: "#DC2626",
        "bg-primary": "#FFFFFF",
        "on-secondary-fixed": "#1a1b21",
        "text-secondary": "#5B6270",
        "tertiary-fixed-dim": "#ffb695",
        "surface-container-low": "#f5f2ff",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c3c0ff",
        "inverse-surface": "#302f39",
        "on-surface-variant": "#464555",
        surface: "#fcf8ff",
        primary: "#3525cd",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-tint": "#4d44e3",
        "on-background": "#1b1b24",
        "on-error-container": "#93000a",
        "on-secondary-container": "#616269",
        "inverse-on-surface": "#f3effc"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-12": "48px",
        "space-1": "4px",
        "space-16": "64px",
        "space-3": "12px",
        "space-8": "32px",
        "space-2": "8px",
        "space-4": "16px",
        "space-32": "128px",
        "space-24": "96px",
        "space-6": "24px",
        base: "4px"
      },
      fontFamily: {
        "display-lg": ["Inter Tight", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-xl": ["Inter Tight", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "heading-md": ["Inter", "sans-serif"],
        "display-xl-mobile": ["Inter Tight", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
        "heading-lg": ["Inter", "sans-serif"],
        "display-md": ["Inter Tight", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["52px", { lineHeight: "1.1", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-xl": ["72px", { lineHeight: "1.05", letterSpacing: "-0.02em", fontWeight: "600" }],
        caption: ["14px", { lineHeight: "1.5", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "heading-md": ["20px", { lineHeight: "1.35", fontWeight: "600" }],
        "display-xl-mobile": ["40px", { lineHeight: "1.1", fontWeight: "600" }],
        code: ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "heading-lg": ["28px", { lineHeight: "1.25", fontWeight: "600" }],
        "display-md": ["36px", { lineHeight: "1.15", fontWeight: "600" }]
      },
      keyframes: {
        'logo-loop': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' }
        },
        'heartbeat': {
          '0%, 100%': { transform: 'scale(1)' },
          '14%': { transform: 'scale(1.15)' },
          '28%': { transform: 'scale(1)' },
          '42%': { transform: 'scale(1.15)' },
          '70%': { transform: 'scale(1)' },
        },
        'shine': {
          '0%': { 'background-position': '100%' },
          '100%': { 'background-position': '-100%' }
        }
      },
      animation: {
        'logo-loop': 'logo-loop 30s linear infinite',
        'heartbeat': 'heartbeat 1.5s ease-in-out infinite',
        'shine': 'shine 5s linear infinite'
      }
    },
  },
  plugins: [],
}
